### ISSUE TITLE
[Atlas Contribution] Tails

### ISSUE THREAD

**Issue by ArtikSnake** [sudokoko/UnionAtlas#4]
{
    	"id": 0,
    	"name": "Tails",
    	"description": "A 2D sprite of Tails from \"Sonic the Hedgehog\"",
    	"group": "ArtikSnake",
    	"center": [
    		766.5,
    		157.5
    	],
    	"path": [
    		[
    			791.5,
    			180.5
    		],
    		[
    			790.5,
    			133.5
    		],
    		[
    			743.5,
    			136.5
    		],
    		[
    			740.5,
    			179.5
    		]
    	]
    }

**Comment by sudokoko** [comment]
@ArtikSnake Thank you for submitting this contribution entry! Unfortunately this entry does not meet all of our criteria for addition. This is due to the following reason(s):

> Please be more accurate when outlining builds. A box for something like a character (such as the one you specified) is not sufficient.

Please re-submit your request once these issues are resolved.
